path: /Users/qiangzai/Documents/workspace/py/ultralytics/dataset # dataset root dir
train: images/train
val: images/val
names:
  0: "A220"
  1: "A330"
  2: "A320/321"
  3: "Boeing737-800"
  4: "Boeing787"
  5: "ARJ21"
  6: "other"
  7: "Boeing737"
  8: "Boeing747"
  9: "Boeing777"
  10: "Boeing787"
  11: "C919"
  12: "A220"
  13: "A321"
  14: "A330"
  15: "A350"
  16: "ARJ21"
  17: "other-airplane"
